name: ecommerce-streaming

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"   # 호스트(로컬 producer.py 등)에서 접속
      # 29092는 컨테이너 내부 네트워크 전용 (Flink 컨테이너가 kafka:29092로 접속)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  jobmanager:
    build:
      context: .
      dockerfile: flink.Dockerfile
    container_name: jobmanager
    ports:
      - "8081:8081"   # Flink 웹 UI -- http://localhost:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        s3.region: ${AWS_REGION}
        execution.checkpointing.storage: filesystem
        state.checkpoints.dir: s3://${S3_BUCKET}/checkpoints/
    env_file:
      - ../.env
    volumes:
      # S3 인증은 .env의 AWS_ACCESS_KEY_ID/SECRET 환경변수로 처리 (Hadoop S3A가 ~/.aws 파일을 안 읽음)
      - ../code/pipelines:/opt/flink/jobs   # raw_zone_consumer.py를 컨테이너 안에서 제출 가능하게

  taskmanager:
    build:
      context: .
      dockerfile: flink.Dockerfile
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        s3.region: ${AWS_REGION}
        execution.checkpointing.storage: filesystem
        state.checkpoints.dir: s3://${S3_BUCKET}/checkpoints/
    env_file:
      - ../.env
    volumes:
      - ../code/pipelines:/opt/flink/jobs

volumes:
  kafka-data:
